DELETE FROM USER_ROLE;
DELETE FROM USERS;
INSERT INTO ROLES VALUES ( 1, 'ROLE_ADMIN' );
INSERT INTO ROLES VALUES ( 2, 'ROLE_SELLER' );
INSERT INTO ROLES VALUES ( 3, 'ROLE_PURCHASER' );
INSERT INTO ROLES VALUES ( 4, 'ROLE_USER');
INSERT INTO USERS VALUES (1, 5, 'user', 'user', '$2a$12$2DmBBaacIy4EPpPrJfl9FO5d63u0ER0uhBL2egRB0KWDnAnbakQlm', 1,1);
INSERT INTO USERS VALUES (2, 5, 'admin', 'admin', '$2y$12$vDvCJgUlo8c3neK72dtOXu.53drY50U68DOsuSa.YJeb8S6K6JM0C', 1,1);
INSERT INTO USER_ROLE VALUES (3,1 );
INSERT INTO USER_ROLE VALUES (2,1 );

INSERT INTO GLAZE_TYPE VALUES ( 1, 'Milk chocolate' );
INSERT INTO GLAZE_TYPE VALUES ( 2, 'Colored chocolate' );
INSERT INTO GLAZE_TYPE VALUES ( 3, 'White chocolate' );
INSERT INTO GLAZE_TYPE VALUES ( 4, 'Dark chocolate' );
INSERT INTO GLAZE_TYPE VALUES ( 5, 'Milk confectionery' );
INSERT INTO GLAZE_TYPE VALUES ( 6, 'Colored confectionery' );
INSERT INTO GLAZE_TYPE VALUES ( 7, 'White confectionery' );
INSERT INTO GLAZE_TYPE VALUES ( 8, 'Dark confectionery' );